#!/usr/bin/env node
/**
 * Bundles engine/engine.ts (+ @mediapipe/tasks-vision) into one self-contained
 * HTML page and writes it to src/engine/engineHtml.generated.ts, which the app
 * loads into a WebView (phones) or an iframe (web). The sign model's web worker
 * (engine/modelWorker.ts) is bundled first and embedded as a string.
 *
 *   node scripts/build-engine.mjs          # regenerate
 *   node scripts/build-engine.mjs --check  # fail if the committed file is stale (CI)
 */
import { build } from 'esbuild';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outFile = join(root, 'src/engine/engineHtml.generated.ts');

const common = {
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: ['es2020'],
  minify: true,
  write: false,
  logLevel: 'warning',
};
const worker = await build({ ...common, entryPoints: [join(root, 'engine/modelWorker.ts')], legalComments: 'none' });
const result = await build({
  ...common,
  entryPoints: [join(root, 'engine/engine.ts')],
  legalComments: 'eof',
  define: { __MODEL_WORKER__: JSON.stringify(worker.outputFiles[0].text) },
  // Escape "</script" inside strings so the bundle can be inlined in HTML.
  supported: { 'inline-script': false },
});
const js = result.outputFiles[0].text;

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
<meta http-equiv="Content-Security-Policy" content="/*ENGINE_CSP*/">
<title>SignSpeak camera</title>
<style>
html,body{margin:0;height:100%;background:#0E1014;overflow:hidden}
#stage{position:relative;width:100%;height:100%}
video,canvas{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}
.mirror{transform:scaleX(-1)}
</style>
</head>
<body>
<div id="stage" aria-hidden="true"><video id="video" playsinline muted></video><canvas id="overlay"></canvas></div>
<script>window.__ISL_ENGINE_CONFIG__=/*ENGINE_CONFIG*/null;</script>
<script>${js}</script>
</body>
</html>
`;

const source = `// Generated by scripts/build-engine.mjs from engine/engine.ts. Do not edit.
// It contains @mediapipe/tasks-vision (Apache-2.0); licence notices are kept in the bundle.
export const ENGINE_HTML: string = ${JSON.stringify(html)};
`;

if (process.argv.includes('--check')) {
  const current = readFileSync(outFile, 'utf8');
  if (current !== source) {
    console.error('src/engine/engineHtml.generated.ts is out of date. Run: npm run build:engine');
    process.exit(1);
  }
  console.log('engine bundle is up to date');
} else {
  writeFileSync(outFile, source);
  console.log(`wrote ${outFile} (${Math.round(source.length / 1024)} KB)`);
}
