/**
 * Landmarks → feature vector, feature spec v1.
 *
 * This is a line-for-line port of ml/signspeak_ml/features/normalize.py, so the
 * app produces exactly the vectors the training pipeline expects. A parity test
 * (features.test.ts) checks it against fixtures generated by the Python code.
 * It runs both in the app and inside the camera engine page.
 */
import {
  COORDS,
  FRAME_DIM,
  HAND_LANDMARK_COUNT,
  LEFT_HAND_PRESENT_INDEX,
  LEFT_HAND_START,
  MIN_SHOULDER_WIDTH,
  POSE_LANDMARKS,
  POSE_PRESENT_INDEX,
  POSE_START,
  RIGHT_HAND_PRESENT_INDEX,
  RIGHT_HAND_START,
} from './featureSpec';

export interface Point3 {
  x: number;
  y: number;
  z: number;
}

const POSE_INDICES = Object.values(POSE_LANDMARKS);

function allFinite(points: readonly Point3[]): boolean {
  return points.every((p) => Number.isFinite(p.x) && Number.isFinite(p.y) && Number.isFinite(p.z));
}

/**
 * @param pose 33 MediaPipe pose landmarks, or null.
 * @param leftHand / rightHand 21 MediaPipe hand landmarks (by MediaPipe handedness on unmirrored frames), or null.
 * @returns 156 floats; all zeros (every presence flag 0) when no usable pose was found.
 */
export function normalizeFrame(
  pose: readonly Point3[] | null,
  leftHand: readonly Point3[] | null,
  rightHand: readonly Point3[] | null,
): Float32Array {
  const out = new Float32Array(FRAME_DIM);
  if (!pose || pose.length !== 33) return out;
  const posePoints = POSE_INDICES.map((i) => pose[i] as Point3);
  if (!allFinite(posePoints)) return out;

  const ls = pose[POSE_LANDMARKS.left_shoulder] as Point3;
  const rs = pose[POSE_LANDMARKS.right_shoulder] as Point3;
  const originX = (ls.x + rs.x) / 2;
  const originY = (ls.y + rs.y) / 2;
  const scale = Math.hypot(ls.x - rs.x, ls.y - rs.y);
  if (!Number.isFinite(scale) || scale < MIN_SHOULDER_WIDTH) return out;

  const write = (points: readonly Point3[], start: number) => {
    points.forEach((p, k) => {
      out[start + k * COORDS] = (p.x - originX) / scale;
      out[start + k * COORDS + 1] = (p.y - originY) / scale;
      out[start + k * COORDS + 2] = p.z / scale;
    });
  };

  write(posePoints, POSE_START);
  out[POSE_PRESENT_INDEX] = 1;

  if (leftHand && leftHand.length === HAND_LANDMARK_COUNT && allFinite(leftHand)) {
    write(leftHand, LEFT_HAND_START);
    out[LEFT_HAND_PRESENT_INDEX] = 1;
  }
  if (rightHand && rightHand.length === HAND_LANDMARK_COUNT && allFinite(rightHand)) {
    write(rightHand, RIGHT_HAND_START);
    out[RIGHT_HAND_PRESENT_INDEX] = 1;
  }
  return out;
}

/** True when a person (pose) was detected in the frame. */
export function signerPresent(values: ArrayLike<number> | null): boolean {
  return values !== null && values.length === FRAME_DIM && (values[POSE_PRESENT_INDEX] ?? 0) > 0.5;
}

/** True when at least one hand was detected. */
export function handsVisible(values: ArrayLike<number> | null): boolean {
  return (
    values !== null &&
    values.length === FRAME_DIM &&
    ((values[LEFT_HAND_PRESENT_INDEX] ?? 0) > 0.5 || (values[RIGHT_HAND_PRESENT_INDEX] ?? 0) > 0.5)
  );
}
