/**
 * Landmarks → feature vector, feature spec v1.
 *
 * This is a line-for-line port of ml/signspeak_ml/features/normalize.py, so the
 * app produces exactly the vectors the training pipeline expects. A parity test
 * (features.test.ts) checks it against fixtures generated by the Python code.
 * It runs both in the app and inside the camera engine page.
 */
import {
  COORDS,
  FRAME_DIM,
  HAND_LANDMARK_COUNT,
  LEFT_HAND_PRESENT_INDEX,
  LEFT_HAND_START,
  MIN_SHOULDER_WIDTH,
  POSE_LANDMARKS,
  POSE_PRESENT_INDEX,
  POSE_START,
  RIGHT_HAND_PRESENT_INDEX,
  RIGHT_HAND_START,
} from './featureSpec';

export interface Point3 {
  x: number;
  y: number;
  z: number;
}

const POSE_INDICES = Object.values(POSE_LANDMARKS);

function allFinite(points: readonly Point3[]): boolean {
  return points.every((p) => Number.isFinite(p.x) && Number.isFinite(p.y) && Number.isFinite(p.z));
}

/**
 * @param pose 33 MediaPipe pose landmarks, or null.
 * @param leftHand / rightHand 21 MediaPipe hand landmarks (by MediaPipe handedness on unmirrored frames), or null.
 * @returns 156 floats; all zeros (every presence flag 0) when no usable pose was found.
 */
export function normalizeFrame(
  pose: readonly Point3[] | null,
  leftHand: readonly Point3[] | null,
  rightHand: readonly Point3[] | null,
): Float32Array {
  const out = new Float32Array(FRAME_DIM);
  if (!pose || pose.length !== 33) return out;
  const posePoints = POSE_INDICES.map((i) => pose[i] as Point3);
  if (!allFinite(posePoints)) return out;

  const ls = pose[POSE_LANDMARKS.left_shoulder] as Point3;
  const rs = pose[POSE_LANDMARKS.right_shoulder] as Point3;
  const originX = (ls.x + rs.x) / 2;
  const originY = (ls.y + rs.y) / 2;
  const scale = Math.hypot(ls.x - rs.x, ls.y - rs.y);
  if (!Number.isFinite(scale) || scale < MIN_SHOULDER_WIDTH) return out;

  const write = (points: readonly Point3[], start: number) => {
    points.forEach((p, k) => {
      out[start + k * COORDS] = (p.x - originX) / scale;
      out[start + k * COORDS + 1] = (p.y - originY) / scale;
      out[start + k * COORDS + 2] = p.z / scale;
    });
  };

  write(posePoints, POSE_START);
  out[POSE_PRESENT_INDEX] = 1;

  if (leftHand && leftHand.length === HAND_LANDMARK_COUNT && allFinite(leftHand)) {
    write(leftHand, LEFT_HAND_START);
    out[LEFT_HAND_PRESENT_INDEX] = 1;
  }
  if (rightHand && rightHand.length === HAND_LANDMARK_COUNT && allFinite(rightHand)) {
    write(rightHand, RIGHT_HAND_START);
    out[RIGHT_HAND_PRESENT_INDEX] = 1;
  }
  return out;
}

/** True when a person (pose) was detected in the frame. */
export function signerPresent(values: ArrayLike<number> | null): boolean {
  return values !== null && values.length === FRAME_DIM && (values[POSE_PRESENT_INDEX] ?? 0) > 0.5;
}

/** True when at least one hand was detected. */
export function handsVisible(values: ArrayLike<number> | null): boolean {
  return (
    values !== null &&
    values.length === FRAME_DIM &&
    ((values[LEFT_HAND_PRESENT_INDEX] ?? 0) > 0.5 || (values[RIGHT_HAND_PRESENT_INDEX] ?? 0) > 0.5)
  );
}

/**
 * Wrist height, in shoulder widths below the shoulders, from which a hand counts
 * as resting (on the lap, or arms hanging down) rather than signing. The hips
 * are about 1.4 below the shoulders.
 */
export const REST_WRIST_Y = 1.2;

/** The hand starting at `start` is in view and raised into signing space. */
export function handRaised(values: ArrayLike<number>, start: number, presentIndex: number): boolean {
  return (values[presentIndex] ?? 0) > 0.5 && (values[start + 1] ?? Infinity) < REST_WRIST_Y;
}

/** At least one hand is in view and raised into signing space (not resting low). */
export function handsRaised(values: ArrayLike<number> | null): boolean {
  return (
    values !== null &&
    values.length === FRAME_DIM &&
    (handRaised(values, LEFT_HAND_START, LEFT_HAND_PRESENT_INDEX) || handRaised(values, RIGHT_HAND_START, RIGHT_HAND_PRESENT_INDEX))
  );
}

const POSE_ORDER = Object.keys(POSE_LANDMARKS);
/** y of the pose tracker's wrists in a frame. */
export const POSE_LEFT_WRIST_Y = POSE_START + POSE_ORDER.indexOf('left_wrist') * COORDS + 1;
export const POSE_RIGHT_WRIST_Y = POSE_START + POSE_ORDER.indexOf('right_wrist') * COORDS + 1;

/**
 * Someone is signing: a hand, or the pose tracker's wrist, is raised into
 * signing space. The hand tracker often loses hands in fast movement (motion
 * blur) while the pose tracker keeps the arm, so the wrist alone counts too.
 * ml/scripts/train_from_landmarks.py (`raised`) uses the same rule.
 */
export function signing(values: ArrayLike<number> | null): boolean {
  if (handsRaised(values)) return true;
  return (
    values !== null &&
    values.length === FRAME_DIM &&
    (values[POSE_PRESENT_INDEX] ?? 0) > 0.5 &&
    ((values[POSE_LEFT_WRIST_Y] ?? Infinity) < REST_WRIST_Y || (values[POSE_RIGHT_WRIST_Y] ?? Infinity) < REST_WRIST_Y)
  );
}
