"""Parity fixtures that pin the app's TypeScript feature code to this implementation.

``shared/fixtures/feature_parity_v1.json`` is generated from :func:`build_parity_fixture`
and read by mobile/src/recognition/__tests__/features.test.ts. A test here fails if
the committed file is out of date.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np

from .normalize import normalize_frame

FIXTURE_PATH = Path(__file__).resolve().parents[3] / "shared" / "fixtures" / "feature_parity_v1.json"


def _pose(rng: np.random.Generator, ls=(0.62, 0.41), rs=(0.38, 0.43)) -> np.ndarray:
    points = np.column_stack(
        [rng.uniform(0.2, 0.8, 33), rng.uniform(0.1, 0.9, 33), rng.uniform(-0.5, 0.5, 33)]
    )
    points[11, :2] = ls
    points[12, :2] = rs
    return points.astype(np.float32)


def _hand(rng: np.random.Generator) -> np.ndarray:
    centre = rng.uniform(0.3, 0.7, 2)
    pts = np.column_stack(
        [centre[0] + rng.normal(0, 0.03, 21), centre[1] + rng.normal(0, 0.03, 21), rng.normal(0, 0.05, 21)]
    )
    return pts.astype(np.float32)


def _as_points(array: np.ndarray | None):
    if array is None:
        return None
    return [
        {"x": None if np.isnan(x) else float(x), "y": None if np.isnan(y) else float(y), "z": float(z)}
        for x, y, z in array[:, :3]
    ]


def build_parity_fixture() -> dict:
    rng = np.random.default_rng(2026)
    degenerate = _pose(rng, ls=(0.5, 0.4), rs=(0.5, 0.4))
    nan_pose = _pose(rng)
    nan_pose[0, 0] = np.nan
    nan_hand = _hand(rng)
    nan_hand[4, 1] = np.nan
    cases = [
        ("both hands", _pose(rng), _hand(rng), _hand(rng)),
        ("left hand only", _pose(rng), _hand(rng), None),
        ("right hand only", _pose(rng), None, _hand(rng)),
        ("no hands", _pose(rng), None, None),
        ("no pose", None, _hand(rng), _hand(rng)),
        ("degenerate shoulders", degenerate, _hand(rng), None),
        ("non-finite pose", nan_pose, None, None),
        ("non-finite hand", _pose(rng), nan_hand, _hand(rng)),
    ]
    return {
        "note": "Generated by ml/scripts/make_feature_fixtures.py. Do not edit by hand. NaN inputs are null.",
        "cases": [
            {
                "name": name,
                "pose": _as_points(p),
                "left": _as_points(left),
                "right": _as_points(right),
                "expected": [round(float(v), 7) for v in normalize_frame(p, left, right)],
            }
            for name, p, left, right in cases
        ],
    }


def fixture_json() -> str:
    return json.dumps(build_parity_fixture()) + "\n"
